#!/usr/bin/with-contenv bash

# make folders
mkdir -p \
    /config/crontabs

# copy config files
[[ ! -f /config/backup.sh ]] && \
	cp /defaults/backup.sh /config/backup.sh
[[ ! -f /config/rclone.conf ]] && \
	touch /config/rclone.conf
# permissions
chmod +x /config/backup.sh
chown -R abc:abc /config
mkdir -p /cache/{rclone,restic} && chown -R abc:abc /cache

# Copy config to new location so it can be mounted read-only
cp /config/rclone.conf /tmp/rclone.conf
chown abc:abc /tmp/rclone.conf
