#!/usr/bin/with-contenv bash
# shellcheck shell=bash

for cron_user in abc root; do
    # make folders
    mkdir -p \
        /config/crontabs

    # if crontabs do not exist in config
    if [[ ! -f "/config/crontabs/${cron_user}" ]]; then
        # copy crontab from defaults (using -n, do not overwrite an existing file)
        cp -n "/defaults/crontab" /config/crontabs/${cron_user}
    fi

    # set permissions and import user crontabs
    lsiown "${cron_user}":"${cron_user}" "/config/crontabs/${cron_user}"
    crontab -u "${cron_user}" "/config/crontabs/${cron_user}"
done
